API_ID: 6134343
API_HASH: 344493a60221b6483e47b00ff1461708
BOT_TOKEN: 5929089968:AAFVBq4UvQfYTKyvpfTWSByIVG_P92Ahd8s


MONGO_URL: mongodb+srv://Saqibpiash:Piash01761@cluster0.uhcsvln.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13414.c212.ap-south-1-1.ec2.cloud.redislabs.com
REDIS_PORT: 13414
REDIS_PASS: LQXPrBCTyaPVLUd7iXCIfTNtfeDrCrG1

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 548699498

OWNER: 548699498

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: jetixbinchat 
# LOG_CHAT: 
LOG_CHAT: -1001894182976



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

