API_ID: 6134343
API_HASH: 344493a60221b6483e47b00ff1461708
BOT_TOKEN: 5929089968:AAFVBq4UvQfYTKyvpfTWSByIVG_P92Ahd8s


MONGO_URL: mongodb+srv://Saqibpiash:Piash01761@cluster0.uhcsvln.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13414.c212.ap-south-1-1.ec2.cloud.redislabs.com
REDIS_PORT: 13414
REDIS_PASS: LQXPrBCTyaPVLUd7iXCIfTNtfeDrCrG1

SESSION_API_ID: 6134343
SESSION_API_HASH: 344493a60221b6483e47b00ff1461708
SESSION_STRING: 1BVtsOHIBu0dMJ_vP9GiyhXwCGOTktnVPeI2-NzSWj5X-V_AF-a44zYRl6pcS0YaPgnqxoboFOlm-YrG4ozxs8enfs3Vm6v1bCCNiYqFVPJjgw4qPf0OdDJl6xDBu5ezF9k7NappQIt3gkA9suuMrIT70UW33UXVrXh19PX-jvWKfL6CkCq6OyBzAO9S7qkjOFWJKX9HckwCnLIDKniEuRKNZEiwgkDdp36v98E3pYSLi3ykredJixfnk7DTEWpvguZIGsCWWcA7hkPwClqu77uxlxRsRy9CsAMcbnw-vjQSVus3xVJ-UehcMc4DuyP1Dwc5pK1IOBzR_fY_0vU4vuRksuw35Q30=

ADMINS: 
  - 548699498

OWNER: 548699498

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: jetixbinchat 
# LOG_CHAT: 
LOG_CHAT: -1001894182976



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

